### ISSUE TITLE
Traceback Error After CHOPPER_TUNE MIN/MAX command

### ISSUE THREAD

**Issue by ReaperXD1** [MRX8024/chopper-resonance-tuner#24]
Hi there, 

I have found another error, after waiting over 2 hours for the testing to finish twice, the terminal output an error;
Traceback (most recent call last):
File "/home/biqu/chopper-resonance-tuner/chopper_plot.py", line 153, in
main()
File "/home/biqu/chopper-resonance-tuner/chopper_plot.py", line 104, in main
data = np.array([[float(row["accel_x"]),
File "/home/biqu/chopper-resonance-tuner/chopper_plot.py", line 105, in
float(row["accel_y"]),
TypeError: float() argument must be a string or a number, not 'NoneType'

Please find attached the klippy log. Is there a way to use stored data to generate the graphs? I can't spare the printer again for another 2 hours hoping it works :(
[klippy (5).log](https://github.com/user-attachments/files/15738406/klippy.5.log)

**Comment by MRX8024** [comment]
Please show `df -h` output, but by the name of the host I can already see what the problem is with memory limit

**Comment by ReaperXD1** [comment]
![image](https://github.com/MRX8024/chopper-resonance-tuner/assets/110054997/553cd1df-9fd5-406f-b0e2-b7097d41e9bf)

**Comment by ReaperXD1** [comment]
Ah okay, I'll give it another try maybe tomorrow.. It's a very loud process

**Comment by MRX8024** [comment]
I didn't notice your last suggestion... if you haven't rebooted the host yet and the csvs are still in /tmp, you can .zip them and I'll generate a graph using the current data

**Comment by ReaperXD1** [comment]
Luckily I found them in my /tmp and transferred them! Thank you very much!
https://drive.google.com/file/d/19LshR2UBQfhbOpDIkJGePYc3pNl5H7x5/view?usp=sharing

**Comment by MRX8024** [comment]
Hello! Sorry for the long wait, Ive had a lot of work fall on me. I analyzed your graphs and also added code, now program would not throw an error, will work with the available data.
[issue24.zip](https://github.com/user-attachments/files/15843793/issue24.zip)
