### ISSUE TITLE
Project is broken - I'd love to use it but I cannot

### ISSUE THREAD

**Issue by oernster** [MRX8024/chopper-resonance-tuner#29]
I run the first command: CHOPPER_TUNE FIND_VIBRATIONS=1
and I get this: {"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.11/site-packages/tornado/web.py\", line 1790, in _execute\n    result = await result\n             ^^^^^^^^^^^^\n\n  File \"/home/pi/moonraker/moonraker/components/application.py\", line 795, in get\n    self.absolute_path = self.validate_absolute_path(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/pi/moonraker-env/lib/python3.11/site-packages/tornado/web.py\", line 2900, in validate_absolute_path\n    raise HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}

I am running latest of everything as of 12/9/2024 and bookworm latest.

**Comment by oernster** [comment]
I've just installed tornado using pip with --break-system-packages to see if that improves matters...

**Comment by oernster** [comment]
no joy

**Comment by MRX8024** [comment]
Hi! Please share the klipper logs manually or via https://coderus.openrepos.net/klipper_logs

**Comment by oernster** [comment]
Please see here: https://coderus.openrepos.net/klipper_logs/366491c219f755498fb08a903d81ee1b

**Comment by oernster** [comment]
or here: 
[klippylogs.zip](https://github.com/user-attachments/files/16974380/klippylogs.zip)

**Comment by oernster** [comment]
I messed with the code in moonraker so I reverted it and this is the latest log.
[moonraker.log](https://github.com/user-attachments/files/16976035/moonraker.log)

**Comment by oernster** [comment]
Works great now - I guess editing the web.py file in moonraker-env under tornado then unediting it fixed it; perhaps there was a hidden character in that file originally, I don't know.  Not your fault though; no errors reported now.  Thanks for your time.  I'll close this issue now.

**Comment by oernster** [comment]
no longer applicable.
