### ISSUE TITLE
4WD Core XY

### ISSUE THREAD

**Issue by O-to-the-o** [MRX8024/chopper-resonance-tuner#35]
Hi 

When running the initial command CHOPPER_TUNE FIND_VIBRATIONS=1  and the others i see no option to specify the motor, in the console it show's "stepper_x", how can i do the tuning for the other 3 steppers ?

Kind regards 
O

**Comment by MRX8024** [comment]
All motors involved in the movement, in the case of corexy these are all 4 motors, change their registers and other parameters during the test. So calibration occurs immediately for all motors of one axis. At the moment, there is no option to software select a specific single stepper motor.

**Comment by O-to-the-o** [comment]
So the settings i get from running it are to be applyed to all 4 drivers ?

**Comment by MRX8024** [comment]
Yes
