### ISSUE TITLE
Unable to obtain 'spi_transfer_response' response

### ISSUE THREAD

**Issue by iz3man** [MRX8024/chopper-resonance-tuner#8]
Today I installed the tool on my Rpi3 running a CoreXY, and started it with "CHOPPER_TUNE FIND_VIBRATIONS=1"
The head starts moving for some time, and then stops with this error message:

```
14:05:52 Unable to obtain 'spi_transfer_response' response
14:05:52 Unable to obtain 'spi_transfer_response' response
14:05:52 Unable to obtain 'spi_transfer_response' response
14:05:50 Speed 67 mm/s on 85.42 mm
14:05:49 Writing raw accelerometer data to /tmp/lis2dw-20240417_140547.csv file
14:05:47 accelerometer measurements started
14:05:47 Speed 66 mm/s on 84.15 mm
14:05:46 Writing raw accelerometer data to /tmp/lis2dw-20240417_140544.csv file
....
....
....
14:03:42 accelerometer measurements started
14:03:42 Command {chop_tune} finished
14:03:40 Running Command {chop_tune}...:
14:03:36 Start find vibration mode, speed: 25 --> 100 mm/s current=800 TBL=2 TOFF=3 HSTRT=5 HEND=0
14:03:36 Final max travel distance = 127.50 mm, position min = -20.00, traveling: -20.00 --> 107.50
14:03:36 Selected 2wd configuration
14:03:36 Selected lis2dw for accelerometer
14:03:36 Selected tmc2209 for stepper_x
```

Anything I can do?

**Comment by MRX8024** [comment]
Please upload klippy.log

**Comment by iz3man** [comment]
Have to upload it directly as it's too big for pastebin & Co. Hope it's readable and includes all needed date.

[klippy.log](https://github.com/MRX8024/chopper-resonance-tuner/files/15011348/klippy.log)

**Comment by MRX8024** [comment]
What speed on canbus?

**Comment by iz3man** [comment]
1m

**Comment by MRX8024** [comment]
Hmm.. I saw you have mcu on a toolhead, have you tried using the accelerometer from there?

**Comment by iz3man** [comment]
I deactivated the accelerometer of the toolhead and used the one in the beacon probe. I'm not sure if that is correct, or if the accelerometer should be placed on the motor itself?!
Nethertheless I now exchanged the USB cable to the canbus adapter and the script ran through! :) Sorry to having bothered you ...

**Comment by iz3man** [comment]
Hmmm. Seems it's still there. I ran "CHOPPER_TUNE MIN_SPEED=42 MAX_SPEED=42" and after 25min it stopped with the same error.


```
18:23:42 Unable to obtain 'spi_transfer_response' response
18:23:41 Unable to obtain 'spi_transfer_response' response
18:23:41 Unable to obtain 'spi_transfer_response' response
```

**Comment by iz3man** [comment]
I now get a lot of these errors. There's something wrong with CAN adapter or the MCU it seems.

```
Resetting prediction variance 2790.703: freq=47983677 diff=2298097 stddev=48000.000
Resetting prediction variance 2791.688: freq=47985818 diff=-5103886 stddev=48000.000
Resetting prediction variance 2792.672: freq=47981059 diff=8021043 stddev=48000.000
Resetting prediction variance 2793.657: freq=47988544 diff=-5913958 stddev=48000.000
Resetting prediction variance 2794.642: freq=47983020 diff=13315993 stddev=48000.000
Resetting prediction variance 2795.626: freq=47995473 diff=-6353403 stddev=48000.000
Resetting prediction variance 2796.610: freq=47989524 diff=-5955205 stddev=48000.000
```

**Comment by maxmadzz** [comment]
I am encountering the same issue with the LIS2DW on the Mellow SB2040, and I am currently unsure how to resolve it. Would it be possible to configure  so that the previous CSV files are preserved, and after resetting the firmware, continue with the testing process?

**Comment by MRX8024** [comment]
With the current functionality of the program, only manually. After the error, go to /tmp and save the files already passed. At this stage, you can manually generate a graph with the available data, and start the next testing starting after them, you will have 2 graphs. Or take a second measurement, combine the files into one folder and start the plotter. The parser simply draws the data that is in /tmp, clearing them every time the macro runs.

-Maxim
