### ISSUE TITLE
Question about mounting the accelerometer

### ISSUE THREAD

**Issue by Habag111** [MRX8024/chopper-resonance-tuner#9]
Hi! This feels like a dumb question, but when you say "Сonnect the accelerometer to the motor by screwing it in", do you mean that the motor should be removed from the printer and an accelerometer should be screwed in to it, or is the motor supposed to stay mounted on the printer?

**Comment by MRX8024** [comment]
Hello.  I did not test with the motor removed) But I can assume that it will start to swing without proper fastening, and this will cause measurement interference.  And also the motor must still experience some kind of load on itself.  Therefore, you just need to attach the accelerometer to an existing stepper motor in your printer, or to the moving part of this axis.

-Maxim
